//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VrDrawing : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerPress
        {
            get
            {
                return SteamVR_Actions.vrDrawing_TriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerDraw
        {
            get
            {
                return SteamVR_Actions.vrDrawing_TriggerDraw;
            }
        }
        
        public virtual SteamVR_Action_Boolean DepthGrip
        {
            get
            {
                return SteamVR_Actions.vrDrawing_DepthGrip;
            }
        }
    }
}
